CREATE TABLE TRUONG (
    MATRUONG CHAR(6) PRIMARY KEY CHECK (REGEXP_LIKE(MATRUONG, 'DH[0-9][0-9][0-9][0-9]')), 
    TENTRUONG VARCHAR(40) NOT NULL UNIQUE, 
    DIACHITRUONG VARCHAR(40), 
    MUCTIEU VARCHAR(40) 
);

CREATE TABLE NGANH (
    MATRUONG CHAR(6) NOT NULL, 
    MANGANH CHAR(5) NOT NULL CHECK (REGEXP_LIKE(MANGANH ,'NG[0-9][0-9][0-9]')), 
    TENNGANH VARCHAR(35) NOT NULL, 
    THONGTINDAURA VARCHAR(35), 
    DECUONGDAOTAO CLOB, 
    PRIMARY KEY(MATRUONG, MANGANH), 
    CONSTRAINT fk_nganh_truong FOREIGN KEY(MATRUONG) 
                               REFERENCES TRUONG(MATRUONG)  
                               ON DELETE CASCADE 
);

CREATE TABLE KHOI (
    TENKHOI CHAR(3) PRIMARY KEY CHECK (REGEXP_LIKE(TENKHOI ,'[A-Z][0-9][0-9]')) 
);

CREATE TABLE THONGTINTUYENSINH (
    MATRUONG CHAR(6) NOT NULL, 
    MANGANH CHAR(5) NOT NULL, 
    TENKHOI CHAR(3) NOT NULL, 
    TYLECHOI DECIMAL(3,2), 
    DIEMCHUANNAMNGOAI DECIMAL(4,2), 
    CHITIEU INT CHECK (CHITIEU > 0), 
    DIEMNV1 DECIMAL(4,2), 
    DIEMNV2 DECIMAL(4,2), 
    DIEMNV3 DECIMAL(4,2), 
    PRIMARY KEY (MATRUONG, MANGANH, TENKHOI), 
    CONSTRAINT fk_ttts_nganh FOREIGN KEY(MATRUONG,MANGANH) 
                             REFERENCES NGANH(MATRUONG,MANGANH) 
                             ON DELETE CASCADE,
    CONSTRAINT fk_ttts_khoi FOREIGN KEY(TENKHOI) 
                            REFERENCES KHOI(TENKHOI) 
                            ON DELETE CASCADE
);

CREATE TABLE MONTHI (
    TENKHOI CHAR(3) NOT NULL, 
    STT CHAR(4) NOT NULL CHECK(REGEXP_LIKE(STT, 'MT[0-9][0-9]')), 
    TENMON VARCHAR(20) NOT NULL, 
    THOIGIANTHI INT CHECK(THOIGIANTHI >0 AND THOIGIANTHI<=180), 
    GIOBATDAU CHAR(5)CHECK(REGEXP_LIKE(GIOBATDAU, '[0-2][0-9]:[0-9][0-9]')), 
    MABUOITHI CHAR(3), 
    PRIMARY KEY(TENKHOI, STT), 
    CONSTRAINT fk_monthi_khoi FOREIGN KEY(TENKHOI) 
                                      REFERENCES KHOI(TENKHOI) 
                                      ON DELETE CASCADE 
); 

CREATE TABLE BUOITHI (
    MABUOITHI CHAR(3) PRIMARY KEY, 
    NGAY DATE, 
    SANGCHIEU INT CHECK(SANGCHIEU = 0 OR SANGCHIEU = 1)  
); 
    
ALTER TABLE MONTHI  ADD CONSTRAINT fk_monthi_buoithi FOREIGN KEY(MABUOITHI) REFERENCES BUOITHI(MABUOITHI) ON DELETE SET NULL;

CREATE TABLE TRUONGTHPT (
    MATRUONGTHPT CHAR(8) PRIMARY KEY CHECK(REGEXP_LIKE(MATRUONGTHPT,'THPT[0-9][0-9][0-9]')), 
    TENTRUONGTHPT VARCHAR(40) NOT NULL 
);

CREATE TABLE NHANSU (
    ID CHAR(7) PRIMARY KEY CHECK(REGEXP_LIKE(ID,'[TS|GT|TT|CB][0-9][0-9][0-9][0-9][0-9]')), 
    CMND CHAR(9) NOT NULL UNIQUE, 
    HOTEN VARCHAR(25) 
);

CREATE TABLE THISINH (
    ID CHAR(7)  PRIMARY KEY CHECK(REGEXP_LIKE(ID, '[TS][0-9][0-9][0-9][0-9][0-9]')), 
    DIACHITHISINH VARCHAR(40), 
    QUEQUAN VARCHAR(40), 
    DIENTHOAI VARCHAR(11), 
    MATRUONGTHPT CHAR(8), 
    CONSTRAINT fk_thising_truongthpt FOREIGN KEY(MATRUONGTHPT) 
                                     REFERENCES TRUONGTHPT(MATRUONGTHPT) ON DELETE SET NULL, 
    CONSTRAINT fk_thising_nhansu FOREIGN KEY(ID) 
                                 REFERENCES NHANSU(ID) 
                                 ON DELETE CASCADE  
);

CREATE TABLE CANBO (
    ID CHAR(7) PRIMARY KEY, 
    CONGVIEC VARCHAR(20) NOT NULL, 
    CONSTRAINT fk_canbo_nhansu FOREIGN KEY(ID) 
                               REFERENCES NHANSU(ID) 
                               ON DELETE CASCADE  
);  

 CREATE TABLE HSTHISINHTHI (
     ID CHAR(7) NOT NULL, 
     MATRUONG CHAR(6) NOT NULL, 
     MANGANH CHAR(5) NOT NULL, 
     TENKHOI CHAR(3) NOT NULL, 
     SBD CHAR(5) NOT NULL CHECK(REGEXP_LIKE(SBD, '[0-9][0-9][0-9][0-9][0-9]')), 
     TONGDIEM DECIMAL(4,2) DEFAULT -1.00 NOT NULL, 
     MADIADIEM CHAR(5) NOT NULL, 
     SOPHONG DECIMAL NOT NULL, 
     PRIMARY KEY(ID, MATRUONG, MANGANH, TENKHOI, SBD), 
     CONSTRAINT fk_hsts_thisinh FOREIGN KEY(ID) 
                                REFERENCES THISINH(ID) 
                                ON DELETE CASCADE,
     CONSTRAINT fk_hsts_nganh FOREIGN KEY(MATRUONG,MANGANH) 
                              REFERENCES NGANH(MATRUONG, MANGANH) 
                              ON DELETE CASCADE,
     CONSTRAINT fk_hsts_khoi FOREIGN KEY(TENKHOI) 
                             REFERENCES KHOI(TENKHOI) 
                             ON DELETE CASCADE
);

CREATE TABLE THISINHNGUYENVONG ( 
    ID CHAR(7 ) NOT NULL ,   
    MATRUONG CHAR(6 ) NOT NULL ,   
    MANGANH CHAR(5 ) NOT NULL ,   
    TENKHOI CHAR(3 ) NOT NULL ,   
    SBD CHAR(5 ) NOT NULL ,   
    MATRUONG2 CHAR(6 ) NOT NULL ,   
    MANGANH2 CHAR(5 ) NOT NULL ,   
    NV23 CHAR(3 ) NOT NULL CHECK (NV23 = 'NV2' OR NV23 = 'NV3') ,    
    PRIMARY KEY (ID, MATRUONG, MANGANH, TENKHOI, SBD, MATRUONG2, MANGANH2), 
    CONSTRAINT fk_tsnv_hsts FOREIGN KEY (ID, MATRUONG, MANGANH, TENKHOI, SBD)    
                            REFERENCES HSTHISINHTHI (ID, MATRUONG, MANGANH, TENKHOI, SBD) 
                            ON DELETE CASCADE ,    
    CONSTRAINT fk_tsnv_nganh FOREIGN KEY (MATRUONG2, MANGANH2)    
                             REFERENCES NGANH (MATRUONG, MANGANH) 
                             ON DELETE CASCADE     
);

CREATE TABLE DIADIEMTHI ( 
    MADIADIEM CHAR(5 ) CHECK (REGEXP_LIKE (MADIADIEM,'DD[0-9][0-9][0-9]')) ,  
    TENDIADIEM VARCHAR2(40 ) ,   
    DIACHIDIADIEM VARCHAR2(40 ) ,    
    PRIMARY KEY (MADIADIEM)    
);

CREATE TABLE PHONGTHI ( 
    MADIADIEM CHAR(5) NOT NULL, 
    SOPHONG INT NOT NULL, 
    TONGSOTHISINH DECIMAL ,  
    MAHANHLANG CHAR(6) ,
    PRIMARY KEY(MADIADIEM, SOPHONG) , 
    CONSTRAINT fk_phongthi_diadiem FOREIGN KEY(MADIADIEM) REFERENCES DIADIEMTHI(MADIADIEM) ON DELETE CASCADE 
); 

ALTER TABLE HSTHISINHTHI ADD CONSTRAINT fk_hsts_diadiemthi FOREIGN KEY(MADIADIEM, SOPHONG) REFERENCES PHONGTHI(MADIADIEM, SOPHONG) ON DELETE CASCADE  

CREATE TABLE THISINHVANG (
    ID CHAR(7) NOT NULL, 
    MATRUONG CHAR(6) NOT NULL, 
    MANGANH CHAR(5) NOT NULL, 
    TENKHOI CHAR(3) NOT NULL, 
    SBD CHAR(5) NOT NULL, 
    MABUOITHI CHAR(3) NOT NULL, 
    PRIMARY KEY(ID, MATRUONG, MANGANH, TENKHOI, SBD, MABUOITHI), 
    CONSTRAINT fk_tsv_hsts FOREIGN KEY(ID, MATRUONG, MANGANH, TENKHOI, SBD) REFERENCES HSTHISINHTHI(ID, MATRUONG, MANGANH, TENKHOI, SBD) ON DELETE CASCADE , 
    CONSTRAINT fk_tsv_mbt FOREIGN KEY(MABUOITHI) REFERENCES BUOITHI(MABUOITHI) ON DELETE CASCADE  
);

CREATE TABLE SOTHISINHCOMAT (
    MADIADIEM CHAR(5), 
    SOPHONG INT NOT NULL , CHECK (SOPHONG > 0), 
    MABUOITHI CHAR(3), 
    PRIMARY KEY (MADIADIEM,SOPHONG,MABUOITHI), 
    SOTHISINHCOMAT INT DEFAULT -1,  
    CONSTRAINT fk_stscm_phongthi FOREIGN KEY (MADIADIEM, SOPHONG)    REFERENCES PHONGTHI (MADIADIEM , SOPHONG) ON DELETE CASCADE ,
    CONSTRAINT fk_stscm_buoithi FOREIGN KEY (MABUOITHI)  REFERENCES BUOITHI(MABUOITHI) ON DELETE CASCADE
);

CREATE TABLE HANHLANG (
    MAHANHLANG CHAR(6) PRIMARY KEY CHECK (REGEXP_LIKE(MAHANHLANG, 'HL[0-9][0-9][0-9][0-9]')) 
); 

ALTER TABLE PHONGTHI ADD CONSTRAINT fk_phongthi_hanhlang FOREIGN KEY(MAHANHLANG) REFERENCES HANHLANG(MAHANHLANG) ON DELETE CASCADE;

CREATE TABLE GIAMTHIGACTHI ( 
    MABUOITHI   CHAR(3) ,   
    MADIADIEM  CHAR(5 ),   
    SOPHONG  INT NOT NULL,   
    GT1 CHAR(7) NOT NULL CHECK(REGEXP_LIKE(GT1,'GT[0-9][0-9][0-9][0-9][0-9]')),   
    GT2 CHAR(7) NOT NULL CHECK(REGEXP_LIKE(GT2,'GT[0-9][0-9][0-9][0-9][0-9]')),   
    PRIMARY KEY(MABUOITHI, MADIADIEM, SOPHONG),   
    CONSTRAINT fk_gt2 FOREIGN KEY(GT2)   REFERENCES CANBO(ID)   ON DELETE CASCADE,     
    CONSTRAINT fk_gt1 FOREIGN KEY(GT1)   REFERENCES CANBO(ID)   ON DELETE CASCADE,   
    CONSTRAINT fk_gtgt_buoithi FOREIGN KEY(MABUOITHI)   REFERENCES BUOITHI(MABUOITHI)   ON DELETE CASCADE,   
    CONSTRAINT fk_gtgt_phongthi FOREIGN KEY(MADIADIEM, SOPHONG)   REFERENCES PHONGTHI(MADIADIEM, SOPHONG)   ON DELETE CASCADE 
);

CREATE TABLE TTVGIAMSAT (
    MABUOITHI CHAR(3), 
    MAHANHLANG CHAR(6),
    TTV1 CHAR(7) NOT NULL CHECK(REGEXP_LIKE(TTV1,'TT[0-9][0-9][0-9][0-9][0-9]')) ,  
    TTV2 CHAR(7) NOT NULL CHECK(REGEXP_LIKE(TTV2,'TT[0-9][0-9][0-9][0-9][0-9]')) , CHECK (TTV1 != TTV2), 
    PRIMARY KEY (MABUOITHI,MAHANHLANG), 
    CONSTRAINT fk_ttvgs_buoithi FOREIGN KEY (MABUOITHI)   REFERENCES BUOITHI(MABUOITHI)   ON DELETE CASCADE,   
    CONSTRAINT fk_ttvgs_hanhlang FOREIGN KEY (MAHANHLANG)   REFERENCES HANHLANG(MAHANHLANG)   ON DELETE CASCADE,   
    CONSTRAINT fk_ttv1 FOREIGN KEY (TTV1)   REFERENCES CANBO(ID)   ON DELETE CASCADE,     
    CONSTRAINT fk_ttv2 FOREIGN KEY (TTV2)   REFERENCES CANBO(ID)   ON DELETE CASCADE  
); 

CREATE TABLE QUYCHE (
    MAQUYCHE CHAR(6) PRIMARY KEY CHECK (REGEXP_LIKE(MAQUYCHE, 'QC[0-9][0-9][0-9]')), 
    MOTA VARCHAR(100) NOT NULL, 
    XULY VARCHAR(100) NOT NULL  
);

CREATE TABLE VIPHAMQUYCHE (
    ID CHAR(7) NOT NULL, 
    MAQUYCHE CHAR(6) NOT NULL, 
    MABUOITHI CHAR(3) NOT NULL, 
    PRIMARY KEY (ID,MAQUYCHE,MABUOITHI), 
    CONSTRAINT FK_VPQCID FOREIGN KEY (ID)   REFERENCES NHANSU(ID)   ON DELETE CASCADE, 
    CONSTRAINT FK_VPQCMAQUYCHE FOREIGN KEY (MAQUYCHE)   REFERENCES QUYCHE(MAQUYCHE)   ON DELETE CASCADE, 
    CONSTRAINT FK_VPQCMABUOITHI FOREIGN KEY (MABUOITHI)   REFERENCES BUOITHI(MABUOITHI)   ON DELETE CASCADE 
); 

CREATE TABLE KETQUATHI (
    ID CHAR(7) NOT NULL, 
    MATRUONG CHAR(6) NOT NULL, 
    MANGANH CHAR(5) NOT NULL, 
    TENKHOI CHAR(3) NOT NULL, 
    SBD CHAR(5) NOT NULL , 
    STT CHAR(4) NOT NULL, 
    DIEMTHI DECIMAL (3,2), CHECK (DIEMTHI <= 10), 
    DIEMPHUCTRA DECIMAL (3,2) DEFAULT -1.00  CHECK (DIEMPHUCTRA <= 10), 
    PRIMARY KEY (ID,MATRUONG,MANGANH,TENKHOI,SBD,STT), 
    CONSTRAINT fk_ketquathi_hsts FOREIGN KEY (ID,MATRUONG,MANGANH,TENKHOI,SBD) REFERENCES HSTHISINHTHI(ID,MATRUONG,MANGANH,TENKHOI,SBD) ON DELETE CASCADE,  
    CONSTRAINT fk_ketquathi_monthi FOREIGN KEY (TENKHOI,STT) REFERENCES MONTHI(TENKHOI,STT) ON DELETE CASCADE 
); 

CREATE SEQUENCE SO_PHONG_AUTO MINVALUE 1 START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE SO_BUOI_AUTO MINVALUE 1 START WITH 1 INCREMENT BY 1;

CREATE INDEX INDEX_NHANSU ON NHANSU(HOTEN);

CREATE INDEX INDEX_BUOITHI ON BUOITHI(NGAY,SANGCHIEU);

CREATE OR REPLACE TRIGGER CAPNHATTONGDIEM
AFTER INSERT ON KETQUATHI
FOR EACH ROW
DECLARE
  CURSOR DT IS SELECT TONGDIEM FROM HSTHISINHTHI WHERE ID= :NEW.ID AND 
            MATRUONG = :NEW.MATRUONG AND
            MANGANH = :NEW.MANGANH AND
            TENKHOI = :NEW.TENKHOI AND
            SBD = :NEW.SBD;
  R_DT  DT%ROWTYPE;
BEGIN
  OPEN DT;
   LOOP
       FETCH DT INTO R_DT;
       EXIT WHEN DT%NOTFOUND;
       IF R_DT.TONGDIEM=-1 THEN
           UPDATE HSTHISINHTHI
              SET HSTHISINHTHI.TONGDIEM = :NEW.DIEMTHI
              WHERE ID= :NEW.ID AND 
                    MATRUONG = :NEW.MATRUONG AND
                    MANGANH = :NEW.MANGANH AND
                    TENKHOI = :NEW.TENKHOI AND
                    SBD = :NEW.SBD;
        ELSE
          UPDATE HSTHISINHTHI
            SET HSTHISINHTHI.TONGDIEM = HSTHISINHTHI.TONGDIEM+:NEW.DIEMTHI
                WHERE ID= :NEW.ID AND 
                      MATRUONG = :NEW.MATRUONG AND
                      MANGANH = :NEW.MANGANH AND
                      TENKHOI = :NEW.TENKHOI AND
                      SBD = :NEW.SBD;
        END IF;
   END LOOP;
   CLOSE DT;
END CAPNHATTONGDIEM;
